# Generated by Django 4.2.6 on 2024-03-15 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 15, 5, 40, 11, 390167, tzinfo=datetime.timezone.utc), verbose_name='published date'),
        ),
    ]
