# Generated by Django 4.2.6 on 2024-03-27 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 27, 18, 9, 18, 853243, tzinfo=datetime.timezone.utc), verbose_name='published date'),
        ),
    ]
